# Configs for pwills.com

title: "QL Portfolio"
name: "QL Portfolio"
email: test@gmail.com
url: "http://qinliudata.github.io"
repository: "qinliudata/qinliudata.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Jekyll configuration
permalink:   /:title/

# Build settings
markdown: kramdown
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
  
# settings for author profile
author:
  name   : "Qin Liu"
  avatar : "/assets/images/headshot.png"
  bio    : "Exploring the world by analyzing data."
  location: "California"
  github : qinliudata
  linkedin: qinliudata
  email  : test@gmail.com


# # comments by disqus
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: ""


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: false
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      # author_profile: true
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
